### ISSUE TITLE
Is the project dead?

### ISSUE THREAD

**Issue by DamienCassou** [cypress-io/eslint-plugin-cypress#100]
Does anyone care about maintaining this project? Are you looking for a maintainer?

**Comment by DamienCassou** [comment]
I've forked the project to https://www.npmjs.com/package/@finsit/eslint-plugin-cypress. If someone someday takes care of the official project, I will happily deprecate my fork and switch back. In the meantime, feel free to open issues and send PRs at https://github.com/foretagsplatsen/eslint-plugin-cypress.

**Comment by jaffrepaul** [comment]
@DamienCassou thank you for your work and support here! It's fantastic have users like you leading the charge when the community needs it. 

Cypress reorganized a bit and we made time and space to better handle the plugins ecosystem. We'd like to bring this plugin into the core Cypress repo so it will be officially maintained. We can move forward with deprecating your fork and switch back, bringing any open issues and PRs back to the main project. 

Let us know how we can help so we can get this on track. 

❤️

**Comment by jaffrepaul** [comment]
Thanks @DamienCassou. I'll work on getting things merged back into the original project and sync with you if needed 👍

**Comment by MikeMcC399** [comment]
@jaffrepaul 

Could you give an update on where the Cypress.io team stands these days?

**Comment by jennifer-shehane** [comment]
Hey @MikeMcC399, this is a good question to bring up. 

We are not currently putting resourcing into maintaining this repo given it is not a critical component of our product and more of a helpful utility. Yet we also had not made clear decisions to *not* support it. 

If there are contributors in the community who are interested in updating this repo for the rest of the community to utilize, we would be open to reviewing those PRs and shepherding those improvements in, but we don't intent to make large updates directly.

**Comment by MikeMcC399** [comment]
@jennifer-shehane 

The repo needs considerable housekeeping done on it as it appears to have fallen behind as far as dependencies are concerned. This is apart from the compatibility to ESLint flat files and deprecation of a set of context methods.

I've submitted the first set of PRs. Please take a look at these when you are able to. These do not provide any benefit for users of the plugin at this time. It's just a case of clearing the ground before doing the work which results in the plugin itself being updated.

**Comment by MikeMcC399** [comment]
- The project is now in a much better condition due to all the PRs merged during the last 5 weeks. `eslint-plugin-cypress` can now be used with the latest version of ESLint (`v9`). 
- https://github.com/cypress-io/eslint-plugin-cypress/issues/146 still needs attention however
- According to the npm registry [eslint-plugin-cypress](https://www.npmjs.com/package/eslint-plugin-cypress) is experiencing weekly downloads of 2.6 to 3.1 Million per week, which is around half of the download numbers for [cypress](https://www.npmjs.com/package/cypress). ([Plugin downloads by version](https://www.npmjs.com/package/eslint-plugin-cypress?activeTab=versions) over the last 7 days are also shown in the statistics.)
- The numbers speak for themselves that the plugin is quite alive!
