### ISSUE TITLE
cypress/unsafe-to-chain-command not exported from the package

### ISSUE THREAD

**Issue by Michsior14** [cypress-io/eslint-plugin-cypress#125]
The latest version (2.13.0) leads to error during eslint execution:

```sh
 error  Definition for rule 'cypress/unsafe-to-chain-command' was not found  cypress/unsafe-to-chain-command
 ```
 
 Looks like it's not exported in index.js file: https://github.com/cypress-io/eslint-plugin-cypress/blob/master/index.js#L11

**Comment by Erik-Outreach** [comment]
Here's a PR to solve the issue: https://github.com/cypress-io/eslint-plugin-cypress/pull/126

**Comment by alistaireverett** [comment]
I think this still isn't fixed, we're getting the same error now using 2.13.3. I think L11 in unsafe-to-chain-command.js should be:

`ruleTester.run('unsafe-to-chain-command', rule, {`

rather than 'action-ends-chain'

https://github.com/cypress-io/eslint-plugin-cypress/blob/c626ad543f65babf1def5caabd1bc9bb9900d2c7/tests/lib/rules/unsafe-to-chain-command.js#L11

**Comment by alistaireverett** [comment]
Made a PR here: https://github.com/cypress-io/eslint-plugin-cypress/pull/135

**Comment by alistaireverett** [comment]
Hmm, just noticed this is in the tests, so should really affect us. Does anyone else still have this issue? Otherwise it might be something we need to fix

**Comment by TD-DO** [comment]
I have this issue and would like to see it resolved, please

**Comment by nagash77** [comment]
@alistaireverett and @TD-DO , please open a new issue with a [reproducible example](https://github.com/cypress-io/cypress-test-tiny) and the Cypress team will be happy to investigate.  You can reference this issue in the description.
