### ISSUE TITLE
Drop or change hard-coded `ecmaVersion`

### ISSUE THREAD

**Issue by brettz9** [cypress-io/eslint-plugin-cypress#215]
I ran into some issues with the Cypress plugin hard-coding ES2019 to my files, not letting me use BigInt literals, for example.

I don't see any reason why Cypress has to have a particular `ecmaVersion` setting. The new default with ESLint is to use `ecmaVersion: 'next'`. If the purpose is to be more careful than the default, ensuring projects will err if they try to use too advanced of a feature for their browsers, one can use https://github.com/keithamus/eslint-plugin-escompat which, while it sets `ecmaVersion` to a recent version (now ES2023), detects the project's browser targets and provides linting errors if too recent of ES features are used.

**Comment by MikeMcC399** [comment]
@brettz9 

Are you suggesting to drop `ecmaVersion: 2019` setting for both `legacy` and `flat` configs?

https://github.com/cypress-io/eslint-plugin-cypress/blob/0e835e938987519240a3a1581b4bc483583bb9be/legacy.js#L27-L30

https://github.com/cypress-io/eslint-plugin-cypress/blob/0e835e938987519240a3a1581b4bc483583bb9be/lib/flat.js#L29-L32

You say you had some issues. Were you able to override the settings in your local ESlint config?

I would definitely be in favor of dropping some backwards-compatible settings and configurations at an appropriate time moving forward.

[v3.0.0](https://github.com/cypress-io/eslint-plugin-cypress/releases/tag/v3.0.0) was a breaking change due to dropping support for ESLint v3, v4, v5 & v6. Apart from that, backwards-compatibility has been maintained. Currently there are still far more [downloads](https://www.npmjs.com/package/eslint-plugin-cypress/v/3.0.0?activeTab=versions) of the `v2.x` plugin compared to the `v3.x` plugin, so uptake is slow-moving!

**Comment by brettz9** [comment]
> @brettz9
> 
> Are you suggesting to drop `ecmaVersion: 2019` setting for both `legacy` and `flat` configs?

Yes.
 
> https://github.com/cypress-io/eslint-plugin-cypress/blob/0e835e938987519240a3a1581b4bc483583bb9be/legacy.js#L27-L30
> 
> https://github.com/cypress-io/eslint-plugin-cypress/blob/0e835e938987519240a3a1581b4bc483583bb9be/lib/flat.js#L29-L32
> 
> You say you had some issues. Were you able to override the settings in your local ESlint config?

Yes.

> I would definitely be in favor of dropping some backwards-compatible settings and configurations at an appropriate time moving forward.
> 
> [v3.0.0](https://github.com/cypress-io/eslint-plugin-cypress/releases/tag/v3.0.0) was a breaking change due to dropping support for ESLint v3, v4, v5 & v6. Apart from that, backwards-compatibility has been maintained. Currently there are still far more [downloads](https://www.npmjs.com/package/eslint-plugin-cypress/v/3.0.0?activeTab=versions) of the `v2.x` plugin compared to the `v3.x` plugin, so uptake is slow-moving!

Yeah, removing it would probably not be backward-compatible, because for some it could be a higher `ecmaVersion` than their default. But setting it higher, e.g., to `2025` may work, but that would depend on their ESLint version supporting that as a value (and would require your periodically updating).

**Comment by MikeMcC399** [comment]
I would prefer to drop support for legacy configs completely and to move to the default `ecmaVersion` at some convenient stage so that the plugin is fully aligned with ESLint itself.

**Comment by MikeMcC399** [comment]
I'm going to suggest removing the `commonLanguageOptions` in the flat config of the next major release of the plugin. ESLint v8 reaches [end-of-life](https://eslint.org/version-support/) on Oct 5, 2024 and that could be a trigger to provide a new release very soon.

I prefer not touching the legacy config though to avoid breaking existing setups, since there is no default for legacy. Users who need a higher version will probably already have an override in their configuration. Users who don't, might get surprised if this is updated. You could however argue either way - to keep or to update.

**Comment by Jikodis** [comment]
Adding `cypressPlugin.configs.recommended` to my existing flat config started throwing linting errors in my code since I use optional chaining. I agree with the decision to remove ecmaVersion in the flat config.

**Comment by MikeMcC399** [comment]
- PR https://github.com/cypress-io/eslint-plugin-cypress/pull/234 is now submitted to remove the `ecmaVersion` from the flat config.

**Comment by MikeMcC399** [comment]
This issue is now resolved in [eslint-plugin-cypress@4.0.0](https://github.com/cypress-io/eslint-plugin-cypress/releases/tag/v4.0.0) as far as flat configurations are concerned.

As described in the [Flat Usage examples](https://github.com/cypress-io/eslint-plugin-cypress/blob/master/FLAT-CONFIG.md#usage-examples):
> This version no longer specifies `languageOptions` for `ecmaVersion` and `sourceType` - see ESLint [JavaScript languageOptions](https://eslint.org/docs/latest/use/configure/language-options#specifying-javascript-options)

Note that since ESLint `v8` has reached end-of-life, it is no longer supported by `eslint-plugin-cypress`.

## Deprecated legacy configuration

No change has been made to the deprecated legacy configuration `parserOptions` for backwards compatibility reasons, and this configuration is considered frozen. When a legacy configuration is used with ESLint `9.1` and above (`ESLINT_USE_FLAT_CONFIG=false`), ESLint outputs a warning similar to the following:

> (node:25528) ESLintRCWarning: You are using an eslintrc configuration file, which is deprecated and support will be removed in v10.0.0. Please migrate to an eslint.config.js file. See https://eslint.org/docs/latest/use/configure/migration-guide for details.
(Use `node --trace-warnings ...` to show where the warning was created)
